# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.1.2'

gem 'newrelic_rpm', git: 'https://github.com/newrelic/newrelic-ruby-agent.git',
                    branch: 'method_level_telemetry'

gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.2', '>= 7.0.2.3'
gem 'sprockets-rails'
gem 'sqlite3', '~> 1.4'
