#!/bin/bash

logfile="log/tester.log"

echo "Pinging endpoint with two errors on one transaction..." >> $logfile

while true; do
  # agents/index
  curl --silent http://localhost:3000/agents >/dev/null

  # go too fast and the agent starts sampling
  sleep 3
done
